#!/bin/sh 
#
#######################################################################
#
#       Samuel M. Haugland July 2017. Run Gemini,Dispec,Totido all 
#       at once. Build an output directory with relevant info.
#
#######################################################################

if test "$#" != 1; then                                                          
echo " Usage: ./do_all RUN_NAME"                                
echo "RUN_NAME is name of output directory"                                
exit                                                                            
fi        

run_name=$1
#Source depth in km
#DO NOT CHANGE THE PLACEMENT OF Source_Depth LINE! gemini_pickle looks for it.
Source_Depth=100
#Gemini formatted Ascii file
Earth_Model=stutprem
#Use ndk_2_gemini to make this file
Source_File=C200707211327A_cmt
#Use gemini_station to make this file
Station_File=gemini_STATIONS
#Frequency bounds in mHz
Minimum_Frequency=0
Maximum_Frequency=200
#Seismogram length in seconds
Seismo_Length=1800
#Damping time should be Seismo_Length / 5 
Damping_Time=360
#1 for P-SV-motion only
#2 for SH-motion only;
#3 for both P-SV- and SH-motion.
What_Motion=1
#d for displacement
#v for velocity
#a for acceleration
#g for accelerometer response.
SeismoType=d
#1 for Viscoelastic 
#0 for Elastic
Dispersion_Switch=0
# Set maximum order 'm' in the sum over spherical harmonics here.
# For example, set 'm=0' if the source is explosion type
# For example, set 'm=2' if the source is moment tensor
MaximumOrder=0
#Angular order bounds
Minimum_Degree=0
Maximum_Degree=10000
Omega_Ell_Window=lw200mhz
# To apply a Butterworth-filter (low and high pass) 
# to the seismogram specify in the string
# the number n of filters and then n times  order and corner frequency.
# For example: One low pass with order 7 and corner frequency 0.01 Hz
#              Two high pass: order 3 and corner freq. 0.008 Hz AND 
#                             order 2 and corner freq. 0.007 Hz
#             -------> type: 1  7  0.01
#                            2  3  0.008  2 0.007
LowpassNumber=1
LowpassOrder=5
LowpassCF=1
HighpassNumber=1
HighpassOrder=0
HighpassCF=0.0025

mkdir ${run_name}
mkdir ${run_name}/green
cp do_all ${run_name}
cp ./gemini.sc ${run_name}
cp ./disp.sc ${run_name}
cp ./to.sc ${run_name}
cp stations/${Station_File} ${run_name}
cp ${Omega_Ell_Window} ${run_name}
cp sources/${Source_File} ${run_name}
cp ${Earth_Model} ${run_name}

echo '#------------------------------------------------------------------#'
echo '#                                                                  #'
echo '#                            Run GEMINI                            #'
echo '#                            ~~~~~~~~~~                            #'  
echo '#                            ~~~~~~~~~~                            #'
echo '#------------------------------------------------------------------#'

(cd ${run_name} && ./gemini.sc ${Earth_Model} ${Omega_Ell_Window} \
                    ${Seismo_Length} ${Damping_Time} ${Minimum_Frequency}\
                    ${Maximum_Frequency} ${Dispersion_Switch} \
                    ${Minimum_Degree} ${Maximum_Degree} ${Source_Depth}\
                    ${What_Motion})

echo '#------------------------------------------------------------------#'
echo '#                                                                  #'
echo '#                            Run DISPEC                            #'
echo '#                            ~~~~~~~~~~                            #'  
echo '#                            ~~~~~~~~~~                            #'
echo '#------------------------------------------------------------------#'

(cd ${run_name} && ./disp.sc ${Source_File} ${Station_File} ${Omega_Ell_Window}\
                              ${MaximumOrder})

echo '#------------------------------------------------------------------#'
echo '#                                                                  #'
echo '#                            Run TOTIDO                            #'
echo '#                            ~~~~~~~~~~                            #'  
echo '#                            ~~~~~~~~~~                            #'
echo '#------------------------------------------------------------------#'

(cd ${run_name} && ./to.sc spec3k ${Seismo_Length} ${SeismoType}\
                     ${LowpassNumber} ${LowpassOrder} ${LowpassCF}\
                     ${HighpassNumber} ${HighpassOrder} ${HighpassCF})

# Samuel Haugland July 2017
# Execute this script to neatly pack gemini output into a folder that 
# gemini_pickle can turn into an obspy pickle file
# Splits a single Ascii output file into a file for each seismogram
(cd ${run_name} && csplit --digits=4  --quiet --prefix=outfile seismogr "/REC/-0" "{*}")
(cd ${run_name} && mv outfile0000 meta_param)
#(cd ${run_name}
#for d in *;
#do
#    chmod -w $d
#done
#chmod +w green)

   


