#!/home/samhaug/anaconda2/bin/python
from obspy import read
from sys import argv
from seispy.convert import gemini_stations

'''
make STATIONS file for gemini
'''

st = read(argv[1])
gemini_stations(st)


