#!/home/samhaug/anaconda2/bin/python

#convert ndk file to mineos ready CMT file.

from sys import argv
f = open(argv[1],'r')
f = f.read()
l = f.strip().split('\n')

evid = l[1].split()[0]
region = '_'.join(l[0].strip().split()[8::])
year = l[0].split()[1].split('/')[0]
month = l[0].split()[1].split('/')[1]
day = l[0].split()[1].split('/')[1]
hour = l[0].split()[2].split(':')[0]
min = l[0].split()[2].split(':')[1]
sec = l[0].split()[2].split(':')[2]
lat = l[0].split()[3]
lon = l[0].split()[4]
mag = l[0].split()[7]
h = l[2].split()[7]
ex = l[3].strip().split()[0]
step = '1.0'
halfd = l[1].split()[-1]
M_o = l[-1].split()[10]
M_rr = l[3].split()[1]
M_tt = l[3].split()[3]
M_pp = l[3].split()[5]
M_rt = l[3].split()[7]
M_rp = l[3].split()[9]
M_tp = l[3].split()[11]
eig1 = ' '.join(l[-1].strip().split()[1:4])
eig2 = ' '.join(l[-1].strip().split()[4:7])
eig3 = ' '.join(l[-1].strip().split()[7:10])
scale_mo = l[-1].strip().split()[10]
strike1,dip1,slip1,strike2,dip2,slip2 = l[-1].split()[11::]

#jday = str(int(month)*12+int(day))
#M_o =  M_o+'e'+M_n
#M_n = '1e'+M_n

out_cmt = open(evid+'_cmt','w')

out_cmt.write('{} {}/{}/{} {}:{}:{} {} {} {} {} {} {}\n'
              .format(evid,year,month,day,hour,min,sec,lat,lon,h,mag,'0.0',region))
out_cmt.write('MLI BW: 0 0 0 MW: 0 0 0 DT=  0  0 {} 0 {} 0 {} 0 \n'
              .format(lat,lon,h))
out_cmt.write('DUR {} EX {} {} 0 {} 0 {} 0 {} 0 {} 0 {} 0\n'
              .format(halfd,ex,M_rr,M_tt,M_pp,M_rt,M_rp,M_tp))
out_cmt.write('{} {} {} {} {} {} {} {} {} {}'
              .format(eig1,eig2,eig3,scale_mo,strike1,dip1,slip1,strike2,dip2,slip2))



