#!/home/samhaug/anaconda2/bin/python

#convert ndk file to mineos ready CMT file.

from sys import argv
f = open(argv[1],'r')
f = f.read()
l = f.strip().split('\n')

## First Line
evid = l[1].split()[0]
month = l[0].split()[1].split('/')[1]
day = l[0].split()[1].split('/')[1]
year = l[0].split()[1].split('/')[0]
hour = l[0].split()[2].split(':')[0]
min = l[0].split()[2].split(':')[1]
sec = l[0].split()[2].split(':')[2]
lat = l[0].split()[3]
lon = l[0].split()[4]
depth = l[0].split()[5]
mb = l[0].split()[6]
ms = l[0].split()[7]
region = ' '.join(l[0].strip().split()[8::])

## Second Line
epii = l[0].split()[0]
c_time = l[2].split()[1]
c_time_e = l[2].split()[2]
c_lat = l[2].split()[3]
c_lat_e = l[2].split()[4]
c_lon = l[2].split()[5]
c_lon_e = l[2].split()[6] 
c_h = l[2].split()[7]
c_h_e = l[2].split()[8]

## Third Line
dur =    l[1].split()[-1]
ex =     l[3].split()[0]
Mrr =    float(l[3].split()[1])
Mrr_e =  float(l[3].split()[2])
Mtt =    float(l[3].split()[3])
Mtt_e =  float(l[3].split()[4])
Mpp =    float(l[3].split()[5])
Mpp_e =  float(l[3].split()[6])
Mrt =    float(l[3].split()[7])
Mrt_e =  float(l[3].split()[8])
Mrp =    float(l[3].split()[9])
Mrp_e =  float(l[3].split()[10])
Mtp =    float(l[3].split()[11])
Mtp_e =  float(l[3].split()[12])

## Fourth Line
eig1 =      float(l[-1].strip().split()[1])
eig1_p =    int(l[-1].strip().split()[2])
eig1_a =    int(l[-1].strip().split()[3])
eig2 =      float(l[-1].strip().split()[4])
eig2_p =    int(l[-1].strip().split()[5])
eig2_a =    int(l[-1].strip().split()[6])
eig3 =      float(l[-1].strip().split()[7])
eig3_p =    int(l[-1].strip().split()[8])
eig3_a =    int(l[-1].strip().split()[9])
scale_mo =  float(l[-1].strip().split()[10])
strike1 =   int(l[-1].split()[11])
dip1 =      int(l[-1].split()[12])
slip1 =     int(l[-1].split()[13])
strike2 =   int(l[-1].split()[14])
dip2 =      int(l[-1].split()[15])
slip2 =     int(l[-1].split()[16])


out_cmt = open(evid+'_cmt','w')

out_cmt.write('{} {}/{}/{} {}:{}:{} {} {} {}{}{}{}\n'
        .format(evid[0:8],month,day,year[2::],hour,min,sec,
                lat,lon,depth,mb,ms,region))
out_cmt.write('{} BW: 5 14  45 MW: 0 0   0 DT=  {} {} {} {} {} {} {} {} \n'
              .format(epii,c_time,c_time_e,c_lat,c_lat_e,c_lon,c_lon_e,
                      c_h,c_h_e))
out_cmt.write(' DUR {} EX {} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f} {:0.2f}\n'
              .format(dur,ex,Mrr,Mrr_e,Mtt,Mtt_e,Mpp,Mpp_e,Mrt,
                      Mrt_e,Mrp,Mrp_e,Mtp,Mtp_e))
out_cmt.write('   {:0.2f} {} {} {:0.2f} {} {} {:0.2f} {} {} {:0.2f} {} {} {} {} {} {}'
              .format(eig1,eig1_p,eig1_a,eig2,eig2_p,eig2_a,eig3,eig3_p,eig3_a,scale_mo,strike1,dip1,slip1,strike2,dip2,slip2))



